#DEV ambiente

app:
  message : this is the property file for the ${spring.application.name}

spring:
  datasource:
    driver-class-name : org.h2.Driver
    url : jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username : sa
    password : sa